### ISSUE TITLE
How to buy games???

### ISSUE THREAD

**Issue by dimutch833** [AmiterCodes/Navebsite-Games#5]

**Comment by dimutch833** [comment]
How to use balance

**Comment by dimutch833** [comment]
I cant buy game

**Comment by dimutch833** [comment]
and how to add to friends

**Comment by dimutch833** [comment]
i fix adding friends :
the navigation bar closes the button
fix:
In profile.aspx:
Just center button

    <div class="grid-container">
        <div class="banner">

            <asp:Image ID="banner" runat="server" CssClass="profile_banner"/>
            <div class="profile_info">
                <asp:Image ID="icon" runat="server" CssClass="profile_icon"/>
                <asp:Label runat="server" CssClass="profile_name" ID="name"></asp:Label>
                <div style="margin-left: auto; margin-right: auto; text-align: center;">
                <asp:Button Text="Add Friend" runat="server" CssClass="button" ID="AddButton" OnClick="AddButton_OnClick"/>
                <asp:Button Text="Remove Friend" runat="server" CssClass="button" Id="RemoveButton" OnClick="RemoveButton_OnClick"/>
                </div>
            </div>
        </div>
        <div class="Activity">
            <Nv:ActivityList runat="server" Id="activities"/>
        </div>
        <div class="Friends">
            <NV:UserList runat="server" ID="friends" ViewStateMode="Enabled" Title="Friends"/>
        </div>
    </div>

Change this:

                <asp:Button Text="Add Friend" runat="server" CssClass="button" ID="AddButton" OnClick="AddButton_OnClick"/>
                <asp:Button Text="Remove Friend" runat="server" CssClass="button" Id="RemoveButton" OnClick="RemoveButton_OnClick"/>
         
To this:

`<div` style="margin-left: auto; margin-right: auto; text-align: center;">
                <asp:Button Text="Add Friend" runat="server" CssClass="button" ID="AddButton" OnClick="AddButton_OnClick"/>
                <asp:Button Text="Remove Friend" runat="server" CssClass="button" Id="RemoveButton" OnClick="RemoveButton_OnClick"/>
 `</div>`

**Comment by dimutch833** [comment]
But i cant buy games

**Comment by dimutch833** [comment]
What the purpose of balance

**Comment by dimutch833** [comment]
i use ccgen to add money to the balance its works normally

when i buy games it redirects to gamepage and not add game to my library

**Comment by AmiterCodes** [comment]
> What the purpose of balance

currently balance doesn't do anything, you can just add to it, I'll soon implement buying games / keys with balance


> i use ccgen to add money to the balance its works normally
> 
> when i buy games it redirects to gamepage and not add game to my library

sounds like a major bug, I'll be on it

**Comment by AmiterCodes** [comment]
Fixed the bug that doesn't allow to buy games, I will now close this issue, if you find any other issues or bugs open an issue for them

**Comment by dimutch833** [comment]
ok Thanks
